AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.2

  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - config/environments/**/*.rb
    - bin/**/*

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '{}'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Layout/IndentArray:
  EnforcedStyle: consistent

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile
    - "**/*.rake"
